#!/bin/bash

#SBATCH --job-name='clean'
#SBATCH --mem=0
#SBATCH -n 4
#SBATCH -N 1
#SBATCH --gres=gpu:1
#SBATCH -C V100|T4
##SBATCH -C P100|V100|T4|K80

# load module
module load python/3.8.9/bmwsifkx

#load enviroment
source ~/work/nlp/venv/bin/activate
cd ~/work/RobustAnomaly/BGL

#vanilla
python BGL_robust_anomaly.py train --robust_method=vanilla --if_clean=clean
python BGL_robust_anomaly.py predict --robust_method=vanilla --if_clean=clean


